# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.sepolia]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
accounts-file = ".starknet_accounts/argent_account.json"
account = "argent_deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true

[sncast.mainnet]
url = "https://starknet-mainnet.g.alchemy.com/v2/Tl6ArGxCd5fmvrYuDrE3n"
account = "argent_deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true
